// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CSN9sMHyEiMryf4beGw7o0CoQABd-cM',
    appId: '1:987958054356:web:8c863532022ee6b2d89a41',
    messagingSenderId: '987958054356',
    projectId: 'project2-fd61b',
    authDomain: 'project2-fd61b.firebaseapp.com',
    storageBucket: 'project2-fd61b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9CSN9sMHyEiMryf4beGw7o0CoQABd-cM',
    appId: '1:987958054356:android:8c863532022ee6b2d89a41',
    messagingSenderId: '987958054356',
    projectId: 'project2-fd61b',
    storageBucket: 'project2-fd61b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9CSN9sMHyEiMryf4beGw7o0CoQABd-cM',
    appId: '1:987958054356:ios:8c863532022ee6b2d89a41',
    messagingSenderId: '987958054356',
    projectId: 'project2-fd61b',
    storageBucket: 'project2-fd61b.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9CSN9sMHyEiMryf4beGw7o0CoQABd-cM',
    appId: '1:987958054356:ios:8c863532022ee6b2d89a41',
    messagingSenderId: '987958054356',
    projectId: 'project2-fd61b',
    storageBucket: 'project2-fd61b.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9CSN9sMHyEiMryf4beGw7o0CoQABd-cM',
    appId: '1:987958054356:web:8c863532022ee6b2d89a41',
    messagingSenderId: '987958054356',
    projectId: 'project2-fd61b',
    authDomain: 'project2-fd61b.firebaseapp.com',
    storageBucket: 'project2-fd61b.firebasestorage.app',
  );
}
